import './App.css';
import AllTeams from './Components/AllTeams';
import Header from './Components/Header';
import React, { Component } from 'react'
import TeamDetails from './Components/TeamDetails';
import Form from './Components/Form';
import { BrowserRouter as Router, Route, Routes } from 'react-router-dom';

// import { getTeams, getPlayers } from './APICalls';

class App extends Component {
  constructor() {
    super();
    this.state = {
      teaminfo: [],
      playerinfo: [],
      userinfo: [],
      rankingsinfo: [],
      leagueId:'1048428157226868736',
      dynastyRankings: [
        { ranking: 1, name: "Justin Jefferson", team: "MIN", position: "WR1", age: 24 },
        { ranking: 2, name: "Ja'Marr Chase", team: "CIN", position: "WR2", age: 24 },
        { ranking: 3, name: "CeeDee Lamb", team: "DAL", position: "WR3", age: 25 },
        { ranking: 4, name: "Breece Hall", team: "NYJ", position: "RB1", age: 23 },
        { ranking: 5, name: "Amon-Ra St. Brown", team: "DET", position: "WR4", age: 24 },
        { ranking: 6, name: "Bijan Robinson", team: "ATL", position: "RB2", age: 22 },
        { ranking: 7, name: "Garrett Wilson", team: "NYJ", position: "WR5", age: 24 },
        { ranking: 8, name: "Marvin Harrison", team: "ARI", position: "WR6", age: 21 },
        { ranking: 9, name: "Jahmyr Gibbs", team: "DET", position: "RB3", age: 22 },
        { ranking: 10, name: "A.J. Brown", team: "PHI", position: "WR7", age: 26 },
        { ranking: 11, name: "Malik Nabers", team: "NYG", position: "WR8", age: 21 },
        { ranking: 12, name: "Jonathan Taylor", team: "IND", position: "RB4", age: 25 },
        { ranking: 13, name: "Christian McCaffrey", team: "SF", position: "RB5", age: 28 },
        { ranking: 14, name: "Puka Nacua", team: "LAR", position: "WR9", age: 23 },
        { ranking: 15, name: "Tyreek Hill", team: "MIA", position: "WR10", age: 30 },
        { ranking: 16, name: "Chris Olave", team: "NO", position: "WR11", age: 23 },
        { ranking: 17, name: "Sam LaPorta", team: "DET", position: "TE1", age: 22 },
        { ranking: 18, name: "Jaylen Waddle", team: "MIA", position: "WR12", age: 25 },
        { ranking: 19, name: "Brandon Aiyuk", team: "SF", position: "WR13", age: 26 },
        { ranking: 20, name: "De'Von Achane", team: "MIA", position: "RB6", age: 22 },
        { ranking: 21, name: "DeVonta Smith", team: "PHI", position: "WR14", age: 25 },
        { ranking: 22, name: "Josh Allen", team: "BUF", position: "QB1", age: 28 },
        { ranking: 23, name: "Travis Etienne", team: "JAC", position: "RB7", age: 25 },
        { ranking: 24, name: "Rome Odunze", team: "CHI", position: "WR15", age: 21 },
        { ranking: 25, name: "Nico Collins", team: "HOU", position: "WR16", age: 25 },
        { ranking: 26, name: "Patrick Mahomes", team: "KC", position: "QB2", age: 29 },
        { ranking: 27, name: "Drake London", team: "ATL", position: "WR17", age: 23 },
        { ranking: 28, name: "Trey McBride", team: "ARI", position: "TE2", age: 24 },
        { ranking: 29, name: "DJ Moore", team: "CHI", position: "WR18", age: 26 },
        { ranking: 30, name: "Michael Pittman", team: "IND", position: "WR19", age: 26 },
        { ranking: 31, name: "Saquon Barkley", team: "PHI", position: "RB8", age: 27 },
        { ranking: 32, name: "Zay Flowers", team: "BAL", position: "WR20", age: 23 },
        { ranking: 33, name: "DK Metcalf", team: "SEA", position: "WR21", age: 26 },
        { ranking: 34, name: "Rashee Rice", team: "KC", position: "WR22", age: 24 },
        { ranking: 35, name: "C.J. Stroud", team: "HOU", position: "QB3", age: 23 },
        { ranking: 36, name: "Jalen Hurts", team: "PHI", position: "QB4", age: 26 },
        { ranking: 37, name: "Kenneth Walker", team: "SEA", position: "RB9", age: 23 },
        { ranking: 38, name: "Lamar Jackson", team: "BAL", position: "QB5", age: 27 },
        { ranking: 39, name: "Jonathon Brooks", team: "CAR", position: "RB10", age: 22 },
        { ranking: 40, name: "Brock Bowers", team: "LV", position: "TE3", age: 22 },
        { ranking: 41, name: "James Cook", team: "BUF", position: "RB11", age: 24 },
        { ranking: 42, name: "Kyren Williams", team: "LAR", position: "RB12", age: 24 },
        { ranking: 43, name: "Kyle Pitts", team: "ATL", position: "TE4", age: 23 },
        { ranking: 44, name: "Joe Burrow", team: "CIN", position: "QB6", age: 27 },
        { ranking: 45, name: "Jordan Addison", team: "MIN", position: "WR23", age: 22 },
        { ranking: 46, name: "Tee Higgins", team: "CIN", position: "WR24", age: 25 },
        { ranking: 47, name: "Deebo Samuel", team: "SF", position: "WR25", age: 28 },
        { ranking: 48, name: "Rachaad White", team: "TB", position: "RB13", age: 25 },
        { ranking: 49, name: "Isiah Pacheco", team: "KC", position: "RB14", age: 24 },
        { ranking: 50, name: "George Pickens", team: "PIT", position: "WR26", age: 24 },  { ranking: 51, name: "Tank Dell", team: "HOU", position: "WR27", age: 24 },
        { ranking: 52, name: "Dalton Kincaid", team: "BUF", position: "TE5", age: 24 },
        { ranking: 53, name: "Anthony Richardson", team: "IND", position: "QB7", age: 22 },
        { ranking: 54, name: "Mark Andrews", team: "BAL", position: "TE6", age: 29 },
        { ranking: 55, name: "Jaxon Smith-Njigba", team: "SEA", position: "WR28", age: 22 },
        { ranking: 56, name: "Josh Jacobs", team: "GB", position: "RB15", age: 26 },
        { ranking: 57, name: "Trey Benson", team: "ARI", position: "RB16", age: 22 },
        { ranking: 58, name: "Jayden Reed", team: "GB", position: "WR29", age: 24 },
        { ranking: 59, name: "Xavier Worthy", team: "KC", position: "WR30", age: 21 },
        { ranking: 60, name: "Kyler Murray", team: "ARI", position: "QB8", age: 27 },
        { ranking: 61, name: "Ladd McConkey", team: "LAC", position: "WR31", age: 22 },
        { ranking: 62, name: "Justin Herbert", team: "LAC", position: "QB9", age: 26 },
        { ranking: 63, name: "Jordan Love", team: "GB", position: "QB10", age: 25 },
        { ranking: 64, name: "Caleb Williams", team: "CHI", position: "QB11", age: 22 },
        { ranking: 65, name: "Mike Evans", team: "TB", position: "WR32", age: 31 },
        { ranking: 66, name: "Davante Adams", team: "LV", position: "WR33", age: 31 },
        { ranking: 67, name: "T.J. Hockenson", team: "MIN", position: "TE7", age: 27 },
        { ranking: 68, name: "Rhamondre Stevenson", team: "NE", position: "RB17", age: 26 },
        { ranking: 69, name: "George Kittle", team: "SF", position: "TE8", age: 30 },
        { ranking: 70, name: "Stefon Diggs", team: "HOU", position: "WR34", age: 30 },
        { ranking: 71, name: "Brian Thomas", team: "JAC", position: "WR35", age: 21 },
        { ranking: 72, name: "Diontae Johnson", team: "CAR", position: "WR36", age: 28 },
        { ranking: 73, name: "Joe Mixon", team: "HOU", position: "RB18", age: 28 },
        { ranking: 74, name: "Jayden Daniels", team: "WAS", position: "QB12", age: 23 },
        { ranking: 75, name: "David Montgomery", team: "DET", position: "RB19", age: 27 },
        { ranking: 76, name: "Christian Kirk", team: "JAC", position: "WR37", age: 27 },
        { ranking: 77, name: "Chris Godwin", team: "TB", position: "WR38", age: 28 },
        { ranking: 78, name: "Cooper Kupp", team: "LAR", position: "WR39", age: 31 },
        { ranking: 79, name: "Tony Pollard", team: "TEN", position: "RB20", age: 27 },
        { ranking: 80, name: "D'Andre Swift", team: "CHI", position: "RB21", age: 25 },
        { ranking: 81, name: "Amari Cooper", team: "CLE", position: "WR40", age: 30 },
        { ranking: 82, name: "Travis Kelce", team: "KC", position: "TE9", age: 34 },
        { ranking: 83, name: "Evan Engram", team: "JAC", position: "TE10", age: 30 },
        { ranking: 84, name: "Javonte Williams", team: "DEN", position: "RB22", age: 24 },
        { ranking: 85, name: "Terry McLaurin", team: "WAS", position: "WR41", age: 29 },
        { ranking: 86, name: "Tyjae Spears", team: "TEN", position: "RB23", age: 23 },
        { ranking: 87, name: "Derrick Henry", team: "BAL", position: "RB24", age: 30 },
        { ranking: 88, name: "Jameson Williams", team: "DET", position: "WR42", age: 23 },
        { ranking: 89, name: "Christian Watson", team: "GB", position: "WR43", age: 25 },
        { ranking: 90, name: "Trevor Lawrence", team: "JAC", position: "QB13", age: 24 },
        { ranking: 91, name: "David Njoku", team: "CLE", position: "TE11", age: 28 },
        { ranking: 92, name: "Dak Prescott", team: "DAL", position: "QB14", age: 31 },
        { ranking: 93, name: "Calvin Ridley", team: "TEN", position: "WR44", age: 29 },
        { ranking: 94, name: "Najee Harris", team: "PIT", position: "RB25", age: 26 },
        { ranking: 95, name: "Brock Purdy", team: "SF", position: "QB15", age: 24 },
        { ranking: 96, name: "Jake Ferguson", team: "DAL", position: "TE12", age: 25 },
        { ranking: 97, name: "Keon Coleman", team: "BUF", position: "WR45", age: 21 },
        { ranking: 98, name: "Blake Corum", team: "LAR", position: "RB26", age: 23 },
        { ranking: 99, name: "Alvin Kamara", team: "NO", position: "RB27", age: 29 },
        { ranking: 100, name: "Brian Robinson Jr.", team: "WAS", position: "RB28", age: 25 },
        { ranking: 101, name: "Zamir White", team: "LV", position: "RB29", age: 25 },
  { ranking: 102, name: "Tua Tagovailoa", team: "MIA", position: "QB16", age: 26 },
  { ranking: 103, name: "Jaylen Warren", team: "PIT", position: "RB30", age: 25 },
  { ranking: 104, name: "Courtland Sutton", team: "DEN", position: "WR46", age: 28 },
  { ranking: 105, name: "Marquise Brown", team: "KC", position: "WR47", age: 27 },
  { ranking: 106, name: "Isaiah Likely", team: "BAL", position: "TE13", age: 24 },
  { ranking: 107, name: "Ricky Pearsall", team: "SF", position: "WR48", age: 24 },
  { ranking: 108, name: "Jared Goff", team: "DET", position: "QB17", age: 29 },
  { ranking: 109, name: "Adonai Mitchell", team: "IND", position: "WR49", age: 21 },
  { ranking: 110, name: "Drake Maye", team: "NE", position: "QB18", age: 22 },
  { ranking: 111, name: "Josh Downs", team: "IND", position: "WR50", age: 23 },
  { ranking: 112, name: "Aaron Jones", team: "MIN", position: "RB31", age: 29 },
  { ranking: 113, name: "MarShawn Lloyd", team: "GB", position: "RB32", age: 23 },
  { ranking: 114, name: "Pat Freiermuth", team: "PIT", position: "TE14", age: 25 },
  { ranking: 115, name: "Keenan Allen", team: "CHI", position: "WR51", age: 32 },
  { ranking: 116, name: "Zach Charbonnet", team: "SEA", position: "RB33", age: 23 },
  { ranking: 117, name: "James Conner", team: "ARI", position: "RB34", age: 29 },
  { ranking: 118, name: "Jerry Jeudy", team: "CLE", position: "WR52", age: 25 },
  { ranking: 119, name: "Romeo Doubs", team: "GB", position: "WR53", age: 24 },
  { ranking: 120, name: "Dallas Goedert", team: "PHI", position: "TE15", age: 29 },
  { ranking: 121, name: "Bryce Young", team: "CAR", position: "QB19", age: 23 },
  { ranking: 122, name: "Chase Brown", team: "CIN", position: "RB35", age: 24 },
  { ranking: 123, name: "Ja'Lynn Polk", team: "NE", position: "WR54", age: 22 },
  { ranking: 124, name: "Xavier Legette", team: "CAR", position: "WR55", age: 23 },
  { ranking: 125, name: "Nick Chubb", team: "CLE", position: "RB36", age: 28 },
  { ranking: 126, name: "DeAndre Hopkins", team: "TEN", position: "WR56", age: 32 },
  { ranking: 127, name: "Zack Moss", team: "CIN", position: "RB37", age: 26 },
  { ranking: 128, name: "Bo Nix", team: "DEN", position: "QB20", age: 24 },
  { ranking: 129, name: "Jerome Ford", team: "CLE", position: "RB38", age: 25 },
  { ranking: 130, name: "Jaylen Wright", team: "MIA", position: "RB39", age: 21 },
  { ranking: 131, name: "J.J. McCarthy", team: "MIN", position: "QB21", age: 21 },
  { ranking: 132, name: "Jermaine Burton", team: "CIN", position: "WR57", age: 23 },
  { ranking: 133, name: "Joshua Palmer", team: "LAC", position: "WR58", age: 25 },
  { ranking: 134, name: "Khalil Shakir", team: "BUF", position: "WR59", age: 24 },
  { ranking: 135, name: "Dalton Schultz", team: "HOU", position: "TE16", age: 28 },
  { ranking: 136, name: "Rashid Shaheed", team: "NO", position: "WR60", age: 26 },
  { ranking: 137, name: "Roman Wilson", team: "PIT", position: "WR61", age: 23 },
  { ranking: 138, name: "Devin Singletary", team: "NYG", position: "RB40", age: 27 },
  { ranking: 139, name: "Deshaun Watson", team: "CLE", position: "QB22", age: 29 },
  { ranking: 140, name: "Baker Mayfield", team: "TB", position: "QB23", age: 29 },
  { ranking: 141, name: "Ben Sinnott", team: "WAS", position: "TE17", age: 22 },
  { ranking: 142, name: "Austin Ekeler", team: "WAS", position: "RB41", age: 29 },
  { ranking: 143, name: "Michael Wilson", team: "ARI", position: "WR62", age: 24 },
  { ranking: 144, name: "Dontayvion Wicks", team: "GB", position: "WR63", age: 23 },
  { ranking: 145, name: "Jakobi Meyers", team: "LV", position: "WR64", age: 27 },
  { ranking: 146, name: "Marvin Mims", team: "DEN", position: "WR65", age: 22 },
  { ranking: 147, name: "Troy Franklin", team: "DEN", position: "WR66", age: 21 },
  { ranking: 148, name: "Ray Davis", team: "BUF", position: "RB42", age: 24 },
  { ranking: 149, name: "Tyler Lockett", team: "SEA", position: "WR67", age: 31 },
  { ranking: 150, name: "Cole Kmet", team: "CHI", position: "TE18", age: 25 },
  { ranking: 151, name: "Luke Musgrave", team: "GB", position: "TE19", age: 24 },
  { ranking: 152, name: "Will Levis", team: "TEN", position: "QB24", age: 25 },
  { ranking: 153, name: "Curtis Samuel", team: "BUF", position: "WR68", age: 28 },
  { ranking: 154, name: "Jahan Dotson", team: "PHI", position: "WR69", age: 24 },
  { ranking: 155, name: "Tucker Kraft", team: "GB", position: "TE20", age: 23 },
  { ranking: 156, name: "Matthew Stafford", team: "LAR", position: "QB25", age: 36 },
  { ranking: 157, name: "Javon Baker", team: "NE", position: "WR70", age: 22 },
  { ranking: 158, name: "Bucky Irving", team: "TB", position: "RB43", age: 22 },
  { ranking: 159, name: "Raheem Mostert", team: "MIA", position: "RB44", age: 32 },
  { ranking: 160, name: "Jalen McMillan", team: "TB", position: "WR71", age: 22 },
  { ranking: 161, name: "Michael Mayer", team: "LV", position: "TE21", age: 23 },
  { ranking: 162, name: "Chuba Hubbard", team: "CAR", position: "RB45", age: 25 },
    { ranking: 163, name: "Kendre Miller", team: "NO", position: "RB46", age: 22 },
    { ranking: 164, name: "Gabe Davis", team: "JAC", position: "WR72", age: 25 },
    { ranking: 165, name: "Kimani Vidal", team: "LAC", position: "RB47", age: 23 },
    { ranking: 166, name: "J.K. Dobbins", team: "LAC", position: "RB48", age: 25 },
    { ranking: 167, name: "Tyrone Tracy", team: "NYG", position: "RB49", age: 24 },
    { ranking: 168, name: "Mike Williams", team: "NYJ", position: "WR73", age: 29 },
    { ranking: 169, name: "Roschon Johnson", team: "CHI", position: "RB50", age: 23 },
    { ranking: 170, name: "Justin Fields", team: "PIT", position: "QB26", age: 25 },
    { ranking: 171, name: "Wan'Dale Robinson", team: "NYG", position: "WR74", age: 23 },
    { ranking: 172, name: "Quentin Johnston", team: "LAC", position: "WR75", age: 23 },
    { ranking: 173, name: "Chig Okonkwo", team: "TEN", position: "TE22", age: 25 },
    { ranking: 174, name: "Will Shipley", team: "PHI", position: "RB51", age: 22 },
    { ranking: 175, name: "Gus Edwards", team: "LAC", position: "RB52", age: 29 },
    { ranking: 176, name: "Kirk Cousins", team: "ATL", position: "QB27", age: 36 },
    { ranking: 177, name: "Cade Otton", team: "TB", position: "TE23", age: 25 },
    { ranking: 178, name: "Darnell Mooney", team: "ATL", position: "WR76", age: 26 },
    { ranking: 179, name: "Ty Chandler", team: "MIN", position: "RB53", age: 26 },
    { ranking: 180, name: "Rashod Bateman", team: "BAL", position: "WR77", age: 24 },
    { ranking: 181, name: "Brandin Cooks", team: "DAL", position: "WR78", age: 31 },
    { ranking: 182, name: "Noah Fant", team: "SEA", position: "TE24", age: 26 },
    { ranking: 183, name: "Tyler Allgeier", team: "ATL", position: "RB54", age: 24 },
    { ranking: 184, name: "Luke McCaffrey", team: "WAS", position: "WR79", age: 23 },
    { ranking: 185, name: "Michael Penix", team: "ATL", position: "QB28", age: 24 },
    { ranking: 186, name: "Malachi Corley", team: "NYJ", position: "WR80", age: 22 },
    { ranking: 187, name: "Ja'Tavion Sanders", team: "CAR", position: "TE25", age: 21 },
    { ranking: 188, name: "DeMario Douglas", team: "NE", position: "WR81", age: 23 },
    { ranking: 189, name: "Audric Estime", team: "DEN", position: "RB55", age: 21 },
    { ranking: 190, name: "Hunter Henry", team: "NE", position: "TE26", age: 29 },
    { ranking: 191, name: "Theo Johnson", team: "NYG", position: "TE27", age: 23 },
    { ranking: 192, name: "Antonio Gibson", team: "NE", position: "RB56", age: 26 },
    { ranking: 193, name: "Jalin Hyatt", team: "NYG", position: "WR82", age: 22 },
    { ranking: 194, name: "Geno Smith", team: "SEA", position: "QB29", age: 33 },
    { ranking: 195, name: "Isaac Guerendo", team: "SF", position: "RB57", age: 24 },
    { ranking: 196, name: "Juwan Johnson", team: "NO", position: "TE28", age: 28 },
    { ranking: 197, name: "Ezekiel Elliott", team: "DAL", position: "RB58", age: 29 },
    { ranking: 198, name: "Braelon Allen", team: "NYJ", position: "RB59", age: 20 },
    { ranking: 199, name: "Elijah Moore", team: "CLE", position: "WR83", age: 24 },
    { ranking: 200, name: "Jaleel McLaughlin", team: "DEN", position: "RB60", age: 24 },
    { ranking: 201, name: "Rico Dowdle", team: "DAL", position: "RB61", age: 26 },
    { ranking: 202, name: "Tyler Conklin", team: "NYJ", position: "TE29", age: 29 },
    { ranking: 203, name: "Keaton Mitchell", team: "BAL", position: "RB62", age: 22 },
    { ranking: 204, name: "Dameon Pierce", team: "HOU", position: "RB63", age: 24 },
    { ranking: 205, name: "Greg Dulcich", team: "DEN", position: "TE30", age: 24 },
    { ranking: 206, name: "Khalil Herbert", team: "CHI", position: "RB64", age: 26 },
    { ranking: 207, name: "Tank Bigsby", team: "JAC", position: "RB65", age: 23 },
    { ranking: 208, name: "Adam Thielen", team: "CAR", position: "WR84", age: 34 },
    { ranking: 209, name: "Treylon Burks", team: "TEN", position: "WR85", age: 24 },
    { ranking: 210, name: "Alexander Mattison", team: "LV", position: "RB66", age: 26 },
    { ranking: 211, name: "Taysom Hill", team: "NO", position: "TE31", age: 34 },
    { ranking: 212, name: "Andrei Iosivas", team: "CIN", position: "WR86", age: 24 },
    { ranking: 213, name: "Tyler Boyd", team: "TEN", position: "WR87", age: 29 },
    { ranking: 214, name: "Trey Palmer", team: "TB", position: "WR88", age: 23 },
    { ranking: 215, name: "Dylan Laube", team: "LV", position: "RB67", age: 24 },
    { ranking: 216, name: "Jonathan Mingo", team: "CAR", position: "WR89", age: 23 },
    { ranking: 217, name: "Noah Brown", team: "WAS", position: "WR90", age: 28 },
    { ranking: 218, name: "Jelani Woods", team: "IND", position: "TE32", age: 25 },
    { ranking: 219, name: "Elijah Mitchell", team: "SF", position: "RB68", age: 26 },
    { ranking: 220, name: "Brenden Rice", team: "LAC", position: "WR91", age: 22 },
    { ranking: 221, name: "K.J. Osborn", team: "NE", position: "WR92", age: 27 },
    { ranking: 222, name: "Devontez Walker", team: "BAL", position: "WR93", age: 23 },
    { ranking: 223, name: "Aaron Rodgers", team: "NYJ", position: "QB30", age: 40 },
    { ranking: 224, name: "A.T. Perry", team: "NO", position: "WR94", age: 24 },
    { ranking: 225, name: "Derek Carr", team: "NO", position: "QB31", age: 33 },
    { ranking: 226, name: "Tutu Atwell", team: "LAR", position: "WR95", age: 24 },
    { ranking: 227, name: "Odell Beckham", team: "MIA", position: "WR96", age: 31 },
    { ranking: 228, name: "Colby Parkinson", team: "LAR", position: "TE33", age: 25 },
    { ranking: 229, name: "Jordan Mason", team: "SF", position: "RB69", age: 25 },
    { ranking: 230, name: "AJ Dillon", team: "GB", position: "RB70", age: 26 },
    { ranking: 231, name: "Rondale Moore", team: "ATL", position: "WR97", age: 24 },
    { ranking: 232, name: "Jonnu Smith", team: "MIA", position: "TE34", age: 29 },
    { ranking: 233, name: "Cedric Tillman", team: "CLE", position: "WR98", age: 24 },
    { ranking: 234, name: "DJ Chark Jr.", team: "LAC", position: "WR99", age: 28 },
    { ranking: 235, name: "Jalen Tolbert", team: "DAL", position: "WR100", age: 25 },
    { ranking: 236, name: "Darius Slayton", team: "NYG", position: "WR101", age: 27 },
    { ranking: 237, name: "Miles Sanders", team: "CAR", position: "RB71", age: 27 },
    { ranking: 238, name: "Daniel Bellinger", team: "NYG", position: "TE35", age: 24 },
    { ranking: 239, name: "Samaje Perine", team: "KC", position: "RB72", age: 29 },
    { ranking: 240, name: "Alec Pierce", team: "IND", position: "WR102", age: 24 },
    { ranking: 241, name: "Malik Washington", team: "MIA", position: "WR103", age: 23 },
    { ranking: 242, name: "Erick All", team: "CIN", position: "TE36", age: 24 },
    { ranking: 243, name: "Skyy Moore", team: "KC", position: "WR104", age: 24 },
    { ranking: 244, name: "Justice Hill", team: "BAL", position: "RB73", age: 26 },
    { ranking: 245, name: "Cade Stover", team: "HOU", position: "TE37", age: 24 },
    { ranking: 246, name: "Gerald Everett", team: "CHI", position: "TE38", age: 30 },
    { ranking: 247, name: "Rasheen Ali", team: "BAL", position: "RB74", age: 23 },
    { ranking: 248, name: "Zay Jones", team: "ARI", position: "WR105", age: 29 },
    { ranking: 249, name: "Kenneth Gainwell", team: "PHI", position: "RB75", age: 25 },
    { ranking: 250, name: "Tre Tucker", team: "LV", position: "WR106", age: 23 },
    { ranking: 251, name: "Isaiah Davis", team: "NYJ", position: "RB76", age: 22 },
    { ranking: 252, name: "Jaheim Bell", team: "NE", position: "TE39", age: 23 },
    { ranking: 253, name: "Sam Darnold", team: "MIN", position: "QB32", age: 27 },
    { ranking: 254, name: "Kendrick Bourne", team: "NE", position: "WR107", age: 29 },
    { ranking: 255, name: "Daniel Jones", team: "NYG", position: "QB33", age: 27 },
    { ranking: 256, name: "Greg Dortch", team: "ARI", position: "WR108", age: 26 },
    { ranking: 257, name: "Jacob Cowing", team: "SF", position: "WR109", age: 23 },
    { ranking: 258, name: "Jamaal Williams", team: "NO", position: "RB77", age: 29 },
    { ranking: 259, name: "D'Onta Foreman", team: "CLE", position: "RB78", age: 28 },
    { ranking: 260, name: "Dawson Knox", team: "BUF", position: "TE40", age: 27 },
    { ranking: 261, name: "Mike Gesicki", team: "CIN", position: "TE41", age: 28 },
    { ranking: 262, name: "Jamari Thrash", team: "CLE", position: "WR110", age: 23 },
    { ranking: 263, name: "Clyde Edwards-Helaire", team: "KC", position: "RB79", age: 25 },
    { ranking: 264, name: "Pierre Strong", team: "CLE", position: "RB80", age: 25 },
    { ranking: 265, name: "Tyler Higbee", team: "LAR", position: "TE42", age: 31 },
    { ranking: 266, name: "Donovan Peoples-Jones", team: "DET", position: "WR111", age: 25 },
    { ranking: 267, name: "John Metchie III", team: "HOU", position: "WR112", age: 24 },
    { ranking: 268, name: "Russell Wilson", team: "PIT", position: "QB34", age: 35 },
    { ranking: 269, name: "Tyler Scott", team: "CHI", position: "WR113", age: 22 },
    { ranking: 270, name: "Parker Washington", team: "JAC", position: "WR114", age: 22 },
    { ranking: 271, name: "Cam Akers", team: "HOU", position: "RB81", age: 25 },
    { ranking: 272, name: "Van Jefferson", team: "PIT", position: "WR115", age: 28 },
    { ranking: 273, name: "Brevin Jordan", team: "HOU", position: "TE43", age: 24 },
    { ranking: 274, name: "Jauan Jennings", team: "SF", position: "WR116", age: 27 },
    { ranking: 275, name: "Sam Howell", team: "SEA", position: "QB35", age: 24 },
    { ranking: 276, name: "Tyquan Thornton", team: "NE", position: "WR117", age: 24 },
    { ranking: 277, name: "Jared Wiley", team: "KC", position: "TE44", age: 23 },
    { ranking: 278, name: "Demarcus Robinson", team: "LAR", position: "WR118", age: 30 },
    { ranking: 279, name: "Gardner Minshew II", team: "LV", position: "QB36", age: 28 },
    { ranking: 280, name: "Luke Schoonmaker", team: "DAL", position: "TE45", age: 25 },
    { ranking: 281, name: "Michael Carter", team: "ARI", position: "RB82", age: 25 },
    { ranking: 282, name: "Will Dissly", team: "LAC", position: "TE46", age: 28 },
    { ranking: 283, name: "Calvin Austin III", team: "PIT", position: "WR119", age: 25 },
    { ranking: 284, name: "JuJu Smith-Schuster", team: "KC", position: "WR120", age: 27 },
    { ranking: 285, name: "Jeff Wilson", team: "MIA", position: "RB83", age: 28 },
    { ranking: 286, name: "Johnny Wilson", team: "PHI", position: "WR121", age: 23 },
    { ranking: 287, name: "Kylen Granson", team: "IND", position: "TE47", age: 26 },
    { ranking: 288, name: "Zach Ertz", team: "WAS", position: "TE48", age: 33 },
    { ranking: 289, name: "Emari Demercado", team: "ARI", position: "RB84", age: 25 },
    { ranking: 290, name: "Hayden Hurst", team: "LAC", position: "TE49", age: 31 },
    { ranking: 291, name: "Jordan Whittington", team: "LAR", position: "WR122", age: 23 },
    { ranking: 292, name: "Trey Lance", team: "DAL", position: "QB37", age: 24 },
    { ranking: 293, name: "Israel Abanikanda", team: "NYJ", position: "RB85", age: 21 },
    { ranking: 294, name: "Harrison Butker", team: "KC", position: "K1", age: 29 },
    { ranking: 295, name: "Kadarius Toney", team: "CLE", position: "WR123", age: 25 },
    { ranking: 296, name: "Dyami Brown", team: "WAS", position: "WR124", age: 24 },
    { ranking: 297, name: "Josh Reynolds", team: "DEN", position: "WR125", age: 29 },
    { ranking: 298, name: "Evan Hull", team: "IND", position: "RB86", age: 23 },
    { ranking: 299, name: "Chris Rodriguez", team: "WAS", position: "RB87", age: 24 },
    { ranking: 300, name: "Casey Washington", team: "ATL", position: "WR126", age: 23 },
    { ranking: 301, name: "Parris Campbell", team: "PHI", position: "WR127", age: 27 },
    { ranking: 302, name: "Tim Patrick", team: "DET", position: "WR128", age: 30 },
    { ranking: 303, name: "Aidan O'Connell", team: "LV", position: "QB38", age: 26 },
    { ranking: 304, name: "Bo Melton", team: "GB", position: "WR129", age: 25 },
    { ranking: 305, name: "Darnell Washington", team: "PIT", position: "TE50", age: 23 },
    { ranking: 306, name: "Noah Gray", team: "KC", position: "TE51", age: 25 },
    { ranking: 307, name: "Baltimore Ravens", team: "BAL", position: "DST1", age: null },
    { ranking: 308, name: "San Francisco 49ers", team: "SF", position: "DST2", age: null },
    { ranking: 309, name: "Dallas Cowboys", team: "DAL", position: "DST3", age: null },
    { ranking: 310, name: "Ainias Smith", team: "PHI", position: "WR130", age: 23 },
    { ranking: 311, name: "Jake Browning", team: "CIN", position: "QB39", age: 28 },
    { ranking: 312, name: "Josh Oliver", team: "MIN", position: "TE52", age: 27 },
    { ranking: 313, name: "Jawhar Jordan", team: "FA", position: "RB88", age: 25 },
    { ranking: 314, name: "Eric Gray", team: "NYG", position: "RB89", age: 24 },
    { ranking: 315, name: "New York Jets", team: "NYJ", position: "DST4", age: null },
    { ranking: 316, name: "Hendon Hooker", team: "DET", position: "QB40", age: 26 },
    { ranking: 317, name: "Buffalo Bills", team: "BUF", position: "DST5", age: null },
    { ranking: 318, name: "Trey Sermon", team: "IND", position: "RB90", age: 25 },
    { ranking: 319, name: "Mac Jones", team: "JAC", position: "QB41", age: 26 },
    { ranking: 320, name: "Allen Lazard", team: "NYJ", position: "WR131", age: 28 },
    { ranking: 321, name: "Justin Tucker", team: "BAL", position: "K2", age: 34 },
    { ranking: 322, name: "Nelson Agholor", team: "BAL", position: "WR132", age: 31 },
    { ranking: 323, name: "Brandon Aubrey", team: "DAL", position: "K3", age: 29 },
    { ranking: 324, name: "Kenny Pickett", team: "PHI", position: "QB42", age: 26 },
    { ranking: 325, name: "Michael Thomas", team: "FA", position: "WR133", age: 31 },
    { ranking: 326, name: "Kareem Hunt", team: "KC", position: "RB91", age: 29 },
    { ranking: 327, name: "Sean Tucker", team: "TB", position: "RB92", age: 22 },
    { ranking: 328, name: "Zach Wilson", team: "DEN", position: "QB43", age: 25 },
    { ranking: 329, name: "Xavier Gipson", team: "NYJ", position: "WR134", age: 23 },
    { ranking: 330, name: "Jeremy Ruckert", team: "NYJ", position: "TE53", age: 24 },
    { ranking: 331, name: "Tyler Bass", team: "BUF", position: "K4", age: 27 },
    { ranking: 332, name: "Kenny McIntosh", team: "SEA", position: "RB93", age: 24 },
    { ranking: 333, name: "Charlie Jones", team: "CIN", position: "WR135", age: 25 },
    { ranking: 334, name: "Washington Commanders", team: "WAS", position: "DST6", age: null },
    { ranking: 335, name: "Bub Means", team: "NO", position: "WR136", age: 23 },
    { ranking: 336, name: "Philadelphia Eagles", team: "PHI", position: "DST7", age: null },
    { ranking: 337, name: "Pittsburgh Steelers", team: "PIT", position: "DST8", age: null },
    { ranking: 338, name: "Evan McPherson", team: "CIN", position: "K5", age: 25 },
    { ranking: 339, name: "Frank Gore", team: "BUF", position: "RB94", age: 22 },
    { ranking: 340, name: "Indianapolis Colts", team: "IND", position: "DST9", age: null },
    { ranking: 341, name: "Los Angeles Chargers", team: "LAC", position: "DST10", age: null },
    { ranking: 342, name: "Dallin Holker", team: "NO", position: "TE54", age: 24 },
    { ranking: 343, name: "Deneric Prince", team: "MIA", position: "RB95", age: 24 }
    ]
    
    
      // dynastyRankings: [
      //   { name: "Justin Jefferson", team: "MIN", ranking: 1 },
      //   { name: "CeeDee Lamb", team: "DAL", ranking: 2 },
      //   { name: "Ja'Marr Chase", team: "CIN", ranking: 3 },
      //   { name: "Amon-Ra St. Brown", team: "DET", ranking: 4 },
      //   { name: "Marvin Harrison", team: "ARI", ranking: 5 },
      //   { name: "Bijan Robinson", team: "ATL", ranking: 6 },
      //   { name: "Breece Hall", team: "NYJ", ranking: 7 },
      //   { name: "Garrett Wilson", team: "NYJ", ranking: 8 },
      //   { name: "A.J. Brown", team: "PHI", ranking: 9 },
      //   { name: "Jahmyr Gibbs", team: "DET", ranking: 10 },
      //   { name: "Malik Nabers", team: "NYG", ranking: 11 },
      //   { name: "Puka Nacua", team: "LAR", ranking: 12 },
      //   { name: "Christian McCaffrey", team: "SF", ranking: 13 },
      //   { name: "Jonathan Taylor", team: "IND", ranking: 14 },
      //   { name: "Tyreek Hill", team: "MIA", ranking: 15 },
      //   { name: "Chris Olave", team: "NO", ranking: 16 },
      //   { name: "Travis Etienne", team: "JAC", ranking: 17 },
      //   { name: "Sam LaPorta", team: "DET", ranking: 18 },
      //   { name: "Jaylen Waddle", team: "MIA", ranking: 19 },
      //   { name: "Drake London", team: "ATL", ranking: 20 },
      //   { name: "Rome Odunze", team: "CHI", ranking: 21 },
      //   { name: "De'Von Achane", team: "MIA", ranking: 22 },
      //   { name: "Brandon Aiyuk", team: "SF", ranking: 23 },
      //   { name: "DeVonta Smith", team: "PHI", ranking: 24 },
      //   { name: "Saquon Barkley", team: "PHI", ranking: 25 },
      //   { name: "DJ Moore", team: "CHI", ranking: 26 },
      //   { name: "Josh Allen", team: "BUF", ranking: 27 },
      //   { name: "Patrick Mahomes", team: "KC", ranking: 28 },
      //   { name: "Michael Pittman", team: "IND", ranking: 29 },
      //   { name: "DK Metcalf", team: "SEA", ranking: 30 },
      //   { name: "Nico Collins", team: "HOU", ranking: 31 },
      //   { name: "Trey McBride", team: "ARI", ranking: 32 },
      //   { name: "Rachaad White", team: "TB", ranking: 33 },
      //   { name: "Jalen Hurts", team: "PHI", ranking: 34 },
      //   { name: "Zay Flowers", team: "BAL", ranking: 35 },
      //   { name: "Kyren Williams", team: "LAR", ranking: 36 },
      //   { name: "C.J. Stroud", team: "HOU", ranking: 37 },
      //   { name: "Isiah Pacheco", team: "KC", ranking: 38 },
      //   { name: "Kenneth Walker", team: "SEA", ranking: 39 },
      //   { name: "Lamar Jackson", team: "BAL", ranking: 40 },
      //   { name: "Brock Bowers", team: "LV", ranking: 41 },
      //   { name: "Tank Dell", team: "HOU", ranking: 42 },
      //   { name: "Jonathon Brooks", team: "CAR", ranking: 43 },
      //   { name: "Mark Andrews", team: "BAL", ranking: 44 },
      //   { name: "James Cook", team: "BUF", ranking: 45 },
      //   { name: "Tee Higgins", team: "CIN", ranking: 46 },
      //   { name: "Kyle Pitts", team: "ATL", ranking: 47 },
      //   { name: "Joe Burrow", team: "CIN", ranking: 48 },
      //   { name: "Dalton Kincaid", team: "BUF", ranking: 49 },
      //   { name: "George Pickens", team: "PIT", ranking: 50 },
      //   { name: "Jordan Addison", team: "MIN", ranking: 51 },
      //   { name: "Xavier Worthy", team: "KC", ranking: 52 },
      //   { name: "Anthony Richardson", team: "IND", ranking: 53 },
      //   { name: "Josh Jacobs", team: "GB", ranking: 54 },
      //   { name: "Rashee Rice", team: "KC", ranking: 55 },
      //   { name: "Brian Thomas", team: "JAC", ranking: 56 },
      //   { name: "Jaxon Smith-Njigba", team: "SEA", ranking: 57 },
      //   { name: "Caleb Williams", team: "CHI", ranking: 58 },
      //   { name: "Deebo Samuel", team: "SF", ranking: 59 },
      //   { name: "Trey Benson", team: "ARI", ranking: 60 },
      //   { name: "Joe Mixon", team: "HOU", ranking: 61 },
      //     { name: "Rhamondre Stevenson", team: "NE", ranking: 62 },
      //     { name: "Derrick Henry", team: "BAL", ranking: 63 },
      //     { name: "D'Andre Swift", team: "CHI", ranking: 64 },
      //     { name: "Travis Kelce", team: "KC", ranking: 65 },
      //     { name: "Davante Adams", team: "LV", ranking: 66 },
      //     { name: "Mike Evans", team: "TB", ranking: 67 },
      //     { name: "Jayden Reed", team: "GB", ranking: 68 },
      //     { name: "Ladd McConkey", team: "LAC", ranking: 69 },
      //     { name: "Amari Cooper", team: "CLE", ranking: 70 },
      //     { name: "Keon Coleman", team: "BUF", ranking: 71 },
      //     { name: "Jordan Love", team: "GB", ranking: 72 },
      //     { name: "T.J. Hockenson", team: "MIN", ranking: 73 },
      //     { name: "Kyler Murray", team: "ARI", ranking: 74 },
      //     { name: "Terry McLaurin", team: "WAS", ranking: 75 },
      //     { name: "George Kittle", team: "SF", ranking: 76 },
      //     { name: "Jayden Daniels", team: "WAS", ranking: 77 },
      //     { name: "Stefon Diggs", team: "HOU", ranking: 78 },
      //     { name: "Tony Pollard", team: "TEN", ranking: 79 },
      //     { name: "David Montgomery", team: "DET", ranking: 80 },
      //     { name: "Javonte Williams", team: "DEN", ranking: 81 },
      //     { name: "Justin Herbert", team: "LAC", ranking: 82 },
      //     { name: "Chris Godwin", team: "TB", ranking: 83 },
      //     { name: "Najee Harris", team: "PIT", ranking: 84 },
      //     { name: "Brian Robinson Jr.", team: "WAS", ranking: 85 },
      //     { name: "Tyjae Spears", team: "TEN", ranking: 86 },
      //     { name: "Christian Watson", team: "GB", ranking: 87 },
      //     { name: "Christian Kirk", team: "JAC", ranking: 88 },
      //     { name: "Zamir White", team: "LV", ranking: 89 },
      //     { name: "Diontae Johnson", team: "CAR", ranking: 90 },
      //     { name: "Cooper Kupp", team: "LAR", ranking: 91 },
      //     { name: "Evan Engram", team: "JAC", ranking: 92 },
      //     { name: "Alvin Kamara", team: "NO", ranking: 93 },
      //     { name: "David Njoku", team: "CLE", ranking: 94 },
      //     { name: "Trevor Lawrence", team: "JAC", ranking: 95 },
      //     { name: "Ricky Pearsall", team: "SF", ranking: 96 },
      //     { name: "Blake Corum", team: "LAR", ranking: 97 },
      //     { name: "Jaylen Warren", team: "PIT", ranking: 98 },
      //     { name: "Dak Prescott", team: "DAL", ranking: 99 },
      //     { name: "Calvin Ridley", team: "TEN", ranking: 100 },
      //     { name: "Aaron Jones", team: "MIN", ranking: 101 },
      //     { name: "Jake Ferguson", team: "DAL", ranking: 102 },
      //     { name: "Adonai Mitchell", team: "IND", ranking: 103 },
      //     { name: "Keenan Allen", team: "CHI", ranking: 104 },
      //     { name: "Marquise Brown", team: "KC", ranking: 105 },
      //     { name: "Brock Purdy", team: "SF", ranking: 106 },
      //     { name: "Jameson Williams", team: "DET", ranking: 107 },
      //     { name: "Tua Tagovailoa", team: "MIA", ranking: 108 },
      //     { name: "Xavier Legette", team: "CAR", ranking: 109 },
      //     { name: "James Conner", team: "ARI", ranking: 110 },
      //     { name: "Dallas Goedert", team: "PHI", ranking: 111 },
      //     { name: "Zach Charbonnet", team: "SEA", ranking: 112 },
      //     { name: "Devin Singletary", team: "NYG", ranking: 113 },
      //     { name: "MarShawn Lloyd", team: "GB", ranking: 114 },
      //     { name: "Drake Maye", team: "NE", ranking: 115 },
      //     { name: "DeAndre Hopkins", team: "TEN", ranking: 116 },
      //     { name: "Jared Goff", team: "DET", ranking: 117 },
      //     { name: "Pat Freiermuth", team: "PIT", ranking: 118 },
      //     { name: "Nick Chubb", team: "CLE", ranking: 119 },
      //     { name: "Jaylen Wright", team: "MIA", ranking: 120 },
      //     { name: "Chase Brown", team: "CIN", ranking: 121 },
      //     { name: "Josh Downs", team: "IND", ranking: 122 },
      //     { name: "Ben Sinnott", team: "WAS", ranking: 123 },
      //     { name: "Ja'Lynn Polk", team: "NE", ranking: 124 },
      //     { name: "Courtland Sutton", team: "DEN", ranking: 125 },
      //     { name: "Dalton Schultz", team: "HOU", ranking: 126 },
      //     { name: "Zack Moss", team: "CIN", ranking: 127 },
      //     { name: "Cole Kmet", team: "CHI", ranking: 128 },
      //     { name: "Luke Musgrave", team: "GB", ranking: 129 },
      //     { name: "Romeo Doubs", team: "GB", ranking: 130 },
      //     { name: "Roman Wilson", team: "PIT", ranking: 131 },
      //     { name: "Jakobi Meyers", team: "LV", ranking: 132 },
      //     { name: "Raheem Mostert", team: "MIA", ranking: 133 },
      //     { name: "Austin Ekeler", team: "WAS", ranking: 134 },
      //     { name: "J.J. McCarthy", team: "MIN", ranking: 135 },
      //     { name: "Jerry Jeudy", team: "CLE", ranking: 136 },
      //     { name: "Jerome Ford", team: "CLE", ranking: 137 },
      //     { name: "Bryce Young", team: "CAR", ranking: 138 },
      //       { name: "Ray Davis", team: "BUF", ranking: 139 },
      //       { name: "Jermaine Burton", team: "CIN", ranking: 140 },
      //       { name: "Deshaun Watson", team: "CLE", ranking: 141 },
      //       { name: "Dontayvion Wicks", team: "GB", ranking: 142 },
      //       { name: "Joshua Palmer", team: "LAC", ranking: 143 },
      //       { name: "Isaiah Likely", team: "BAL", ranking: 144 },
      //       { name: "Jahan Dotson", team: "PHI", ranking: 145 },
      //       { name: "Gabe Davis", team: "JAC", ranking: 146 },
      //       { name: "Troy Franklin", team: "DEN", ranking: 147 },
      //       { name: "Tucker Kraft", team: "GB", ranking: 148 },
      //       { name: "Will Levis", team: "TEN", ranking: 149 },
      //       { name: "Javon Baker", team: "NE", ranking: 150 },
      //       { name: "Baker Mayfield", team: "TB", ranking: 151 },
      //       { name: "Kirk Cousins", team: "ATL", ranking: 152 },
      //       { name: "Tyler Lockett", team: "SEA", ranking: 153 },
      //       { name: "Chuba Hubbard", team: "CAR", ranking: 154 },
      //       { name: "Rashid Shaheed", team: "NO", ranking: 155 },
      //       { name: "Rico Dowdle", team: "DAL", ranking: 156 },
      //       { name: "Kendre Miller", team: "NO", ranking: 157 },
      //       { name: "Bo Nix", team: "DEN", ranking: 158 },
      //       { name: "Ja'Tavion Sanders", team: "CAR", ranking: 159 },
      //       { name: "Jaleel McLaughlin", team: "DEN", ranking: 160 },
      //       { name: "Matthew Stafford", team: "LAR", ranking: 161 },
      //       { name: "Marvin Mims", team: "DEN", ranking: 162 },
      //       { name: "Curtis Samuel", team: "BUF", ranking: 163 },
      //       { name: "Gus Edwards", team: "LAC", ranking: 164 },
      //       { name: "Noah Fant", team: "SEA", ranking: 165 },
      //       { name: "Roschon Johnson", team: "CHI", ranking: 166 },
      //       { name: "Khalil Shakir", team: "BUF", ranking: 167 },
      //       { name: "Tyler Allgeier", team: "ATL", ranking: 168 },
      //       { name: "Jalen McMillan", team: "TB", ranking: 169 },
      //       { name: "Kimani Vidal", team: "LAC", ranking: 170 },
      //       { name: "Luke McCaffrey", team: "WAS", ranking: 171 },
      //       { name: "Bucky Irving", team: "TB", ranking: 172 },
      //       { name: "Cade Otton", team: "TB", ranking: 173 },
      //       { name: "Antonio Gibson", team: "NE", ranking: 174 },
      //       { name: "Michael Mayer", team: "LV", ranking: 175 },
      //       { name: "Tyrone Tracy", team: "NYG", ranking: 176 },
      //       { name: "Michael Penix", team: "ATL", ranking: 177 },
      //       { name: "Mike Williams", team: "NYJ", ranking: 178 },
      //       { name: "Khalil Herbert", team: "CHI", ranking: 179 },
      //       { name: "Braelon Allen", team: "NYJ", ranking: 180 },
      //       { name: "Malachi Corley", team: "NYJ", ranking: 181 },
      //       { name: "DeMario Douglas", team: "NE", ranking: 182 },
      //       { name: "Quentin Johnston", team: "LAC", ranking: 183 },
      //       { name: "Michael Wilson", team: "ARI", ranking: 184 },
      //       { name: "Audric Estime", team: "DEN", ranking: 185 },
      //       { name: "Baltimore Ravens", team: "BAL", ranking: 186 },
      //       { name: "Rashod Bateman", team: "BAL", ranking: 187 },
      //       { name: "Buffalo Bills", team: "BUF", ranking: 188 },
      //       { name: "Ty Chandler", team: "MIN", ranking: 189 },
      //       { name: "Wan'Dale Robinson", team: "NYG", ranking: 190 },
      //       { name: "Dallas Cowboys", team: "DAL", ranking: 191 },
      //       { name: "Hunter Henry", team: "NE", ranking: 192 },
      //       { name: "Darnell Mooney", team: "ATL", ranking: 193 },
      //       { name: "Brandin Cooks", team: "DAL", ranking: 194 },
      //       { name: "J.K. Dobbins", team: "LAC", ranking: 195 },
      //       { name: "Keaton Mitchell", team: "BAL", ranking: 196 },
      //       { name: "San Francisco 49ers", team: "SF", ranking: 197 },
      //       { name: "Chigoziem Okonkwo", team: "TEN", ranking: 198 },
      //       { name: "Ezekiel Elliott", team: "DAL", ranking: 199 },
      //       { name: "Jalin Hyatt", team: "NYG", ranking: 200 },
      //       { name: "Will Shipley", team: "PHI", ranking: 201 },
      //       { name: "Justin Tucker", team: "BAL", ranking: 202 },
      //       { name: "Geno Smith", team: "SEA", ranking: 203 },
      //       { name: "Justin Fields", team: "PIT", ranking: 204 },
      //       { name: "Juwan Johnson", team: "NO", ranking: 205 },
      //       { name: "Pittsburgh Steelers", team: "PIT", ranking: 206 },
      //       { name: "Dameon Pierce", team: "HOU", ranking: 207 },
      //       { name: "Greg Dulcich", team: "DEN", ranking: 208 },
      //       { name: "New York Jets", team: "NYJ", ranking: 209 },
      //       { name: "Dylan Laube", team: "LV", ranking: 210 }
      //     ]
      
      
    }
  }
  updateLeagueId = (newLeagueId) => {
    this.setState({leagueId: newLeagueId}, this.fetchData)

  }
   
  componentDidMount() {
    this.fetchData()
  }
    fetchData = () => {
      const{ leagueId } = this.state

        const getPlayers = fetch('http://localhost:3000/players/nfl')
            .then(response => {
                if (!response.ok) {
                    throw new Error('Network response was not ok');
                }
                return response.json();
            });

        const getTeams = fetch(`https://api.sleeper.app/v1/league/${leagueId}/rosters`)
            .then(response => {
                if (!response.ok) {
                    throw new Error('Network response was not ok');
                }
                return response.json();
            });
        const getUsers = fetch(`https://api.sleeper.app/v1/league/${leagueId}/users`)
            .then(response => {
                if (!response.ok) {
                    throw new Error('Network response was not ok');
                }
                return response.json();
            });
          
        
            Promise.all([getPlayers, getTeams, getUsers])
            .then(([call1, call2, call3, call4]) => {
                this.setState({
                    playerinfo: call1,
                    teaminfo: call2,
                    userinfo: call3,
                    loading: false,
                });
                // console.log(this.state)
            })
            .catch(error => {
                this.setState({
                    error: error.message,
                    loading: false,
                });
            });
  }

  render() {
    return (
      <Router>
        <main>
          <Header />
          <Form onSubmit={this.updateLeagueId} />

          <Routes>
            {/* Route to the team list */}
            <Route
              path="/"
              element={
                <AllTeams
                  rankings={this.state.dynastyRankings}
                  users={this.state.userinfo}
                  fantasyteam={this.state.teaminfo}
                  players={this.state.playerinfo}
                />
              }
            />

            {/* Route to display the details for a particular team */}
            <Route
              path="/team/:owners_id"
              element={
                <TeamDetails
                   rankings={this.state.dynastyRankings}
                  users={this.state.userinfo}
                  fantasyteam={this.state.teaminfo}
                  players={this.state.playerinfo}
                />
              }
            />
          </Routes>
        </main>
      </Router>
    );
  }
}



export default App;


